import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./styles/global.scss";
import SidebarLayout from "./components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <SidebarLayout>{children}</SidebarLayout>
        </AntdRegistry>
      </body>
    </html>
  );
}
