import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./styles/global.scss";
import "antd/dist/reset.css"; // core styles
import "@ant-design/compatible"; // react-19 shim

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
